ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
TARGET=IrTvControl
BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf

ARDUINO_LIBS = IRemote
AVRDUDE_ARD_BAUDRATE =  57600

include /usr/share/arduino/custom/Arduino.mk
