#!/usr/bin/python
import serial
import sys

options = ["s","f","b","cw","ccw"]

ser = serial.Serial('/dev/ttyUSB0', 9600)
if len(sys.argv) <= 1:
	print "Valid arguments"
	print options	
	
for arg in sys.argv:
	if not "car" in arg:
		print options.index(arg)
		try:
			ser.write(chr(options.index(arg))+'\n')
		except ValueError:
			print "Argument Unknown:"
			print arg
			print "Valid arguments"
			print options	
